### ISSUE TITLE
step 3. Creating Integration is confusing

### ISSUE THREAD

**Issue by rafaeltuelho** [integr8ly/tutorial-web-app-walkthroughs#43]
The sequence of substeps (selecting Fruit Custom API connector and data mapper) does not represent what you have to follow in the UI. Which is confusing for a person who is new to the Fuse Online UI.

**Comment by pwright** [comment]
@rafaeltuelho  Are you referring to https://github.com/integr8ly/tutorial-web-app-walkthroughs/blob/master/walkthroughs/1A-integrate-event-and-api-driven-apps/walkthrough.adoc#3-creating-an-integration ? 
Can you suggest a change that might help? or a step that you found was incorrect?

thanks for this feedback?

**Comment by rafaeltuelho** [comment]
So,

the confusing step in this walkthrough is the **3.8 "Choose Walkthrough 1A CRUD Connection as the Finish Connection."**. At this time the **"Walkthrough 1A CRUD Connection"** does not exist yet. Although we created an API Client Connector before (in Customizations UI), we still need to create a Connection for it. So steps missing is how to create a Connection which uses that Custom API Connector.

**Comment by pwright** [comment]
thanks, I need to run thru this again, but have you not created the **Walkthrough 1A CRUD Connection** as part of [2.2,](https://github.com/integr8ly/tutorial-web-app-walkthroughs/blob/master/walkthroughs/1A-integrate-event-and-api-driven-apps/walkthrough.adoc#22-creating-http-connection-to-crud-app) specifically step 8?

**Comment by rafaeltuelho** [comment]
@finp you are right! I revised the steps and I realized I may have missed following the step "**2.2. Creating HTTP connection to CRUD App**"

That's why I could not find it in step 3.8.

Thanks.

**Comment by pwright** [comment]
Closing, please reopen if there is still an issue.
