### ISSUE TITLE
walkthrough 2, step 3.2) 3scale Private Base URL placeholder not replaced

### ISSUE THREAD

**Issue by rafaeltuelho** [integr8ly/tutorial-web-app-walkthroughs#44]
On walkthrough "Managing and protecting APIs using API management" Task 3
Step 3.2 "Adding the Fuse Aggregation App Endpoint to Red Hat 3scale" the "3scale Private Base URL" placeholder is not being replace by the real URL.

See screenshot:
![image](https://user-images.githubusercontent.com/39063/54454790-0559f400-4739-11e9-87f5-71ade78ea8ff.png)

**Comment by pwright** [comment]
Cannot replicate:
![image](https://user-images.githubusercontent.com/5154224/54492628-2bf66700-48c0-11e9-9992-3bd40111f2fb.png)

Is it possible that the app was rebuilding? ie were you able to confirm that task 2 was completed, ie:

After waiting for the build and deployment to complete, check Flights Endpoint. Are more than 8 flights displayed?

**Comment by pwright** [comment]
closing, cannot reproduce, @rafaeltuelho  please reopen if you feel this issue can be addressed here
