### ISSUE TITLE
Minor issue with 1A-integrate-event walkthrough - consistency between step 1 in 2.1-2.3 and 3.1

### ISSUE THREAD

**Issue by bfitzpat** [integr8ly/tutorial-web-app-walkthroughs#66]
While working through the first walkthrough (FANTASTIC by the way - I love these), I noticed a minor inconsistency...

Each set of steps in 2.1, 2.2, and 2.3 starts with:
```
1. Log in to the Red Hat Fuse Online console.
```

And then goes on to do things in the Fuse Online console.

But 3.1 starts with 

```
1. Select Integrations from the left hand menu.
```

Should we revise that to include a step for logging into the Red Hat Fuse Online console again for consistency?

**Comment by pwright** [comment]
fixed
