### ISSUE TITLE
Minor issue with 1A-integrate event walkthrough -- warnings on importing openapi spec

### ISSUE THREAD

**Issue by bfitzpat** [integr8ly/tutorial-web-app-walkthroughs#68]
When going through the 1A walkthrough, I noticed that there were some warnings when we do 2.1, step 4. 

1. Unable to determine the scheme to use: OpenAPI specification does not provide a `schemes' definition and the specification was uploaded so the originating URL is lost.
2. Operation PUT /api/fruits/{id} does not provide a response schema for code 201
3. Operation DELETE /api/fruits/{id} does not provide a response schema for code 204 

![image](https://user-images.githubusercontent.com/530878/56817811-82ca5700-6803-11e9-9581-a8b4799a170b.png)

If these warnings are meant to be there for future steps the user can resolve (might be a worthwhile follow-up walkthrough?), it would be good to mention that. As a user, I'm not sure I want to see warnings here that I don't know what to do with. It reduces confidence that this is a good course of action. 

If these warnings are not meant to be here, we should possibly do something to resolve them in the imported openapi specfication.

**Comment by pwright** [comment]
closed in favor of https://github.com/syndesisio/syndesis/issues/7238
