### ISSUE TITLE
Error Red Hat Fuse Online

### ISSUE THREAD

**Issue by rbaumgar** [integr8ly/tutorial-web-app-walkthroughs#84]
Error: Red Hat Fuse Online, Unable to provision. Please contact your Red Hat representative.

when clicking on Get Started at "Integrating message-oriented middleware with a RESTful API using AMQ Online"
Fuse Online is marked with ! on the right hand side.
Going to Service Catalog on the top link to Fuse Online works perfect.
environment is provisioned through  RHPDS.

**Comment by rbaumgar** [comment]
looks like it is a RHPDS problem. 
I made an uninstall/install of integr8ly... 
Now it works perfect.

I found also some troubles under installation...

**Comment by pwright** [comment]
closing
