### ISSUE TITLE
walkthroughs-2: Step 1: 7. Authorize your Github Account

### ISSUE THREAD

**Issue by rbaumgar** [integr8ly/tutorial-web-app-walkthroughs#85]
When I run walkthroughs-2 for the first user, e.g evals01, everthing works perfect.
When I run it later for another user, e.g. evals02, I fail at step 1: 7. Authorize your Github Account
https://launcher-sso-launcher.apps.wien-e496.openshiftworkshop.com returns

We're sorry...
Federated identity returned by github is already linked to another user.

Problem is understandable, because I have only one place where I register the Github OAuth App...
see https://github.com/integr8ly/installation#add-the-generated-authorization-callback-url-to-github-oauth

How should this work with multiple users?
Do I miss something?

**Comment by david-martin** [comment]
Hi @rbaumgar.

If I'm understanding you correctly, you are trying to link your github account to both evals01 & evals02 users.
If this is the case, it won't work.
You can only link a github account to a single user in the instance of keycloak that's running in your cluster.
This is a limitation of keycloak, but I'm sure there are good reasons for that.

You can always remove the Identity Provider Link from the evals01 user in keycloak so that another user can link to your github account.

**Comment by rbaumgar** [comment]
This is what I understand. But how can I work with this environment when I have multiple user doing the same at the same time. E.g. having a workshop with 20 attendees? 
Should launcher work differently?

**Comment by pwright** [comment]
A workshop with 20 attendees with 20 different github accounts? that wouldn't be a problem, right?

**Comment by rbaumgar** [comment]
@finp How to setup? when I have only ONE Github OAuth

**Comment by pwright** [comment]
Only one user needs to set up the oauth app at https://github.com/settings/developers
And that github user logged in as evals01 can then perform a walkthrough.
But evals02 must have a different github account to perform the walkthrough, even tho evals02 does not need to set up an oauth app at https://github.com/settings/developers

So, one github user needs to set up oauth app, but the other users of the cluster only require unique github accounts, make sense?

**Comment by rbaumgar** [comment]
@finp I see. The problem is that I tested with the same Github user...

**Comment by pwright** [comment]
@rbaumgar  I think we need to document this better, https://issues.jboss.org/browse/INTLY-2764 
ok to close this issue?

**Comment by rbaumgar** [comment]
Yes.

Paul Wright <notifications@github.com> schrieb am Di., 23. Juli 2019, 12:18:
